// apps/astro/src/components/AnimeCard.tsx
import { MotionDiv } from "./MotionDiv.tsx";
import type { AnimeProp } from "../types.ts";

interface Prop {
  anime: AnimeProp;
  index: number;
}

const variants = {
  hidden: { opacity: 0 },
  visible: { opacity: 1 },
};

function AnimeCard({ anime, index }: Prop) {
  return (
    <MotionDiv
      variants={variants}
      initial="hidden"
      animate="visible"
      transition={{
        delay: index * 0.25,
        ease: "easeInOut",
        duration: 0.5,
      }}
      viewport={{ amount: 0 }}
      className="max-w-sm rounded relative w-full"
    >
      <div className="relative w-full h-[37vh]">
        <img
          src={`https://shikimori.one${anime.image.original}`}
          alt={anime.name}
          className="rounded-xl"
        />
      </div>
      <div className="py-4 flex flex-col gap-3">
        <div className="flex justify-between items-center gap-1">
          <h2 className="font-bold text-white text-xl line-clamp-1 w-full">
            {anime.name}
          </h2>
          <div className="py-1 px-2 bg-[#161921] rounded-sm">
            <p className="text-white text-sm font-bold capitalize">
              {anime.kind}
            </p>
          </div>
        </div>
        <div className="flex gap-4 items-center">
          <div className="flex flex-row gap-2 items-center">
            <img
              src="./episodes.svg"
              alt="episodes"
              width={20}
              height={20}
              className="object-contain"
            />
            <p className="text-base text-white font-bold">
              {anime.episodes || anime.episodes_aired}
            </p>
          </div>
          <div className="flex flex-row gap-2 items-center">
            <img
              src="./star.svg"
              alt="star"
              width={18}
              height={18}
              className="object-contain"
            />
            <p className="text-base font-bold text-[#FFAD49]">{anime.score}</p>
          </div>
        </div>
      </div>
    </MotionDiv>
  );
}

export default AnimeCard;

// apps/sveltekit/src/components/AnimeCard.svelte
<script lang="ts">
import { fade } from 'svelte/transition';
import type { AnimeProp } from '../types';
import {sineInOut} from "svelte/easing";

export let anime: AnimeProp;
export let index: number;
</script>

<div transition:fade={{ delay: index * 0.25, duration: 50, easing: sineInOut }} class="max-w-sm rounded relative w-full">
	<div class="relative h-[37vh] w-full">
		<img src={`https://shikimori.one${anime.image.original}`} alt={anime.name} class="rounded-xl" />
	</div>
	<div class="flex flex-col gap-3 py-4">
		<div class="flex items-center justify-between gap-1">
			<h2 class="line-clamp-1 w-full text-xl font-bold text-white">
				{index} {anime.name}
			</h2>
			<div class="rounded-sm bg-[#161921] px-2 py-1">
				<p class="text-sm font-bold capitalize text-white">
					{anime.kind}
				</p>
			</div>
		</div>
		<div class="flex items-center gap-4">
			<div class="flex flex-row items-center gap-2">
				<img src="./episodes.svg" alt="episodes" width={20} height={20} class="object-contain" />
				<p class="text-base font-bold text-white">
					{anime.episodes || anime.episodes_aired}
				</p>
			</div>
			<div class="flex flex-row items-center gap-2">
				<img src="./star.svg" alt="star" width={18} height={18} class="object-contain" />
				<p class="text-base font-bold text-[#FFAD49]">{anime.score}</p>
			</div>
		</div>
	</div>
</div>
