// apps/sveltekit/src/components/Footer.svelte
<footer class="sm:px-16 py-4 px-8 flex justify-between items-center gap-2 flex-wrap bg-[#161921]">
    <p class="text-base font-bold text-white">@2023</p>
    <img
            src="./logo.svg"
            alt="logo"
            width={47}
            height={44}
            class="object-contain"
    />
    <div class="flex items-center gap-6">
        <img
                src="./tiktok.svg"
                alt="logo"
                width={19}
                height={19}
                class="object-contain"
        />
        <img
                src="./instagram.svg"
                alt="logo"
                width={19}
                height={19}
                class="object-contain"
        />
        <img
                src="./twitter.svg"
                alt="logo"
                width={19}
                height={19}
                class="object-contain"
        />
    </div>
</footer>

// apps/nextjs/components/Footer.tsx
import Image from "next/image";

function Footer() {
  return (
    <footer className="sm:px-16 py-4 px-8 flex justify-between items-center gap-2 flex-wrap bg-[#161921]">
      <p className="text-base font-bold text-white">@2023</p>
      <Image
        src="./logo.svg"
        alt="logo"
        width={47}
        height={44}
        className="object-contain"
      />
      <div className="flex items-center gap-6">
        <Image
          src="./tiktok.svg"
          alt="logo"
          width={19}
          height={19}
          className="object-contain"
        />
        <Image
          src="./instagram.svg"
          alt="logo"
          width={19}
          height={19}
          className="object-contain"
        />
        <Image
          src="./twitter.svg"
          alt="logo"
          width={19}
          height={19}
          className="object-contain"
        />
      </div>
    </footer>
  );
}

export default Footer;
